# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  port: 5433

development:
  <<: *default
  database: test_rails_app_dev
  password: password

production:
  <<: *default
  database: test_rails_app
